dbt_impala_demo:
  target: dev
  outputs:
    dev:
     type: impala
     host: coordinator-dev-user-vw-dub.dw-lgim-dev-dublin.k9sz-n8au.cloudera.site
     port: 443
     dbname: dbt_poc
     schema: dbt_poc
     user: d00_cdpbbgdfx_svc
     password: Password123!
     auth_type: ldap
     use_http_transport: true
     use_ssl: true
     http_path: cliservice
